--DDL PARA LA DEFINICION DE LA TABLA INQUILINOS
CREATE TABLE INQUILINOS 
(
    ID_INQUILINO NUMBER NOT NULL,
    NOMBRE VARCHAR2(200),
    A_PATERNO VARCHAR2(200),
    A_MATERNO VARCHAR2(200),
    TELEFONO VARCHAR2(200),
    FECHA_PAGO VARCHAR(200),
    CONSTRAINT INQUILINOS_PK PRIMARY KEY(ID_INQUILINO)
);

--DDL PARA LA DEFINICION DE LA TABLA DUEÑOS
CREATE TABLE DUENIOS
(
    ID_DUENIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(200),
    A_PATERNO VARCHAR2(200),
    A_MATERNO VARCHAR2(200),
    TELEFONO VARCHAR2(200),
    CUENTA VARCHAR(200),
    CONSTRAINT DUENIOS_PK PRIMARY KEY(ID_DUENIO)
);

--DDL PARA LA DEFINICION DE LA TABLA PROPIEDADES
CREATE TABLE PROPIEDADES
(
    ID_PROPIEDAD NUMBER NOT NULL,
    DIRECCION VARCHAR2(200),
    DUENIO_ID NUMBER NOT NULL,
    DISPONIBILIDAD NUMBER,
    TIPO_PROPIEDAD VARCHAR2(200),
    PRECIO FLOAT,
    CONSTRAINT PROPIEDADES_PK PRIMARY KEY(ID_PROPIEDAD),
    CONSTRAINT PROPIEDADES_DUENIOS_FK FOREIGN KEY(DUENIO_ID)
        REFERENCES DUENIOS(ID_DUENIO)
);


--DDL PARA LA DEFINICION DE LA TABLA CONTRATOS
CREATE TABLE CONTRATOS
(
    ID_CONTRATO NUMBER NOT NULL,
    PROPIEDAD_ID NUMBER NOT NULL,
    DUENIO_ID NUMBER NOT NULL,
    INQUILINO_ID NUMBER NOT NULL,
    DURACION NUMBER,
    TIPO_CONTRATO VARCHAR(200),
    CONSTRAINT CONTRATOS_PK PRIMARY KEY(ID_CONTRATO),
    CONSTRAINT CONTRATOS_PROPIEDADES_FK FOREIGN KEY(PROPIEDAD_ID)
        REFERENCES PROPIEDADES(ID_PROPIEDAD),
    CONSTRAINT CONTRATOS_DUENIOS_FK FOREIGN KEY(DUENIO_ID)
        REFERENCES DUENIOS(ID_DUENIO),
    CONSTRAINT CONTRATOS_INQUILINOS_FK FOREIGN KEY(INQUILINO_ID)
        REFERENCES INQUILINOS(ID_INQUILINO)
);


--DDL PARA LA DEFINICION DE LA TABLA MANTENIMIENTOS
CREATE TABLE MANTENIMIENTOS
(
    ID_MANTENIMIENTO NUMBER NOT NULL,
    PROPIEDAD_ID NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(200),
    COSTO FLOAT,
    FECHA_REPORTE DATE,
    ESTADO_FINALIZADO NUMBER,
    CONSTRAINT MANTENIMIENTOS_PK PRIMARY KEY(ID_MANTENIMIENTO),
    CONSTRAINT MANTENIMIENTOS_PROPIEDADES_FK FOREIGN KEY(PROPIEDAD_ID)
        REFERENCES PROPIEDADES(ID_PROPIEDAD)
);

--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE_INQUILINO"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
    
--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE_DUENIO"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;

--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE_PROPIEDAD"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
    
--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE_CONTRATO"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
    
--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE_MANTENIMIENTO"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;


--CONTINUAR CON INSERCION DE DATOS 

--DML PARA LOS DATOS DE LA TABLA INQUILINOS

INSERT INTO INQUILINOS (ID_INQUILINO, NOMBRE, A_PATERNO, A_MATERNO, TELEFONO, FECHA_PAGO)
VALUES
(sequence_inquilino.nextval, 'Sergio', 'Leal', 'Garate', '2228901710', 'Pimeros');


INSERT INTO INQUILINOS (ID_INQUILINO, NOMBRE, A_PATERNO, A_MATERNO, TELEFONO, FECHA_PAGO)
VALUES
(sequence_inquilino.nextval, 'Alberto', 'Mártinez', 'Liahut', '2228901710', 'Mediados');


--DML PARA LOS DATOS DE LA TABLA DUENIOS

INSERT INTO DUENIOS (ID_DUENIO, NOMBRE, A_PATERNO, A_MATERNO, TELEFONO, CUENTA)
VALUES
(sequence_duenio.nextval, 'Elizabeth', 'Silva', 'Espinosa', '2228901710', '2545213256');


INSERT INTO DUENIOS (ID_DUENIO, NOMBRE, A_PATERNO, A_MATERNO, TELEFONO, CUENTA)
VALUES
(sequence_duenio.nextval, 'Carlos', 'Márquez', 'Bazán', '2228901710', '52154236558');


--DML PARA LOS DATOS DE LA TABLA PROPIEDADES
INSERT INTO PROPIEDADES (ID_PROPIEDAD, DIRECCION, DUENIO_ID, DISPONIBILIDAD, TIPO_PROPIEDAD, PRECIO)
VALUES
(sequence_propiedad.nextval, 'Higuera 3 depto 102 Torres de Mayorazgo, Puebla, Puebla', 1, 0, 'Departamento', 1200000.00);


INSERT INTO PROPIEDADES (ID_PROPIEDAD, DIRECCION, DUENIO_ID, DISPONIBILIDAD, TIPO_PROPIEDAD, PRECIO)
VALUES
(sequence_propiedad.nextval, 'Higuera 2 depto 002 Torres de Mayorazgo, Puebla, Puebla', 2, 0, 'Departamento', 1300000.00);


--DML PARA LOS DATOS DE LA TABLA PROPIEDADES
INSERT INTO CONTRATOS (ID_CONTRATO, PROPIEDAD_ID, DUENIO_ID, INQUILINO_ID, DURACION, TIPO_CONTRATO)
VALUES
(sequence_contrato.nextval, 1, 1, 2, 3, 'RENTA');

INSERT INTO CONTRATOS (ID_CONTRATO, PROPIEDAD_ID, DUENIO_ID, INQUILINO_ID, DURACION, TIPO_CONTRATO)
VALUES
(sequence_contrato.nextval, 2, 2, 1, 6, 'RENTA');


--DML PARA LOS DATOS DE LA TABLA PROPIEDADES
INSERT INTO MANTENIMIENTOS (ID_MANTENIMIENTO, PROPIEDAD_ID, DESCRIPCION, COSTO, FECHA_REPORTE, ESTADO_FINALIZADO)
VALUES
(sequence_mantenimiento.nextval, 2, 'Falta Pintura', 565.50, TO_DATE('2024-01-05 12:30:00','YYYY-MM-DD HH24:mi:ss'), 1);


INSERT INTO MANTENIMIENTOS (ID_MANTENIMIENTO, PROPIEDAD_ID, DESCRIPCION, COSTO, FECHA_REPORTE, ESTADO_FINALIZADO)
VALUES
(sequence_mantenimiento.nextval, 2, 'Vidrio roto', 1000.60, TO_DATE('2024-01-10 13:30:00','YYYY-MM-DD HH24:mi:ss'), 0);



--APARTADO PARA USO DE CODIGOS 

SELECT * FROM propiedades;





--GUARDAR DATOS
COMMIT;


