/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-01-17 20:32:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.silva.app.rutas.models.*;
import com.google.gson.Gson;

public final class altaRuta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.silva.app.rutas.models");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.google.gson.Gson");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    //recuperamos la lista de choferes que seteamos en el request desde el servlet
    List<Chofer> choferes =  (List<Chofer>) request.getAttribute("choferes");
    List<Camion> camiones =  (List<Camion>) request.getAttribute("camiones");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-2.2.4.min.js\"\r\n");
      out.write("                integrity=\"sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=\"\r\n");
      out.write("                crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css\">\r\n");
      out.write("    <script src=\"//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("            <div class=\"navbar-header\" id=\"div1\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\"\r\n");
      out.write("                    data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                                    <a class=\"navbar-brand\" href=\"#\" id=\"enlace1\">Rutas App</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"\r\n");
      out.write("                            aria-haspopup=\"true\" aria-expanded=\"false\">Choferes<span\r\n");
      out.write("                                class=\"caret\"></span></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/choferes/listar\">Lista Choferes</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/choferes/alta\">Alta Chofer</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"\r\n");
      out.write("                            aria-haspopup=\"true\" aria-expanded=\"false\">Camiones<span\r\n");
      out.write("                                class=\"caret\"></span></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/camiones/listar\">Lista Camiones</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/camiones/alta\">Alta Camion</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"\r\n");
      out.write("                            aria-haspopup=\"true\" aria-expanded=\"false\">Rutas<span\r\n");
      out.write("                                class=\"caret\"></span></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/rutas/alta\">Alta Ruta</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div><!-- /.navbar-collapse -->\r\n");
      out.write("        </div><!-- /.container-fluid -->\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container body-content\">\r\n");
      out.write("        <script src=\"//maps.googleapis.com/maps/api/js?key=AIzaSyCWeeateTaYGqsHhNcmoDfT7Us-vLDZVPs&amp;sensor=false&amp;language=en\"></script>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <h2>Iniciar Ruta</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          <!--  div[style]>input:text[name=Cadena][id=Cadena]-->\r\n");
      out.write("            <div style=\"display: block;\"><input type=\"text\" name=\"\" id=\"txtEsOD\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"\">Chofer</label>\r\n");
      out.write("                    <select name=\"chofer\" id=\"chofer\" class=\"form-control\">\r\n");
      out.write("                        <option selected=\"true\" disabled=\"disabled\">seleccionar</option>\r\n");
      out.write("                        ");
 for(Chofer c: choferes){ 
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print(c.getId());
      out.write('"');
      out.write('>');
      out.print(c.getNombre());
      out.write("</option>\r\n");
      out.write("                            ");
}
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("                            <label for=\"\">Origen</label>\r\n");
      out.write("                            <input type=\"text\" name=\"origen\" id=\"origen\" class=\"form-control\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"idOrigen\" id=\"idOrigen\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <button class=\"btn btn-primary btn-xs\" style=\"margin-top: 30px;\" onclick=\"getDireccion(1);\">Obtener Datos</button>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"\">Fecha Salida</label>\r\n");
      out.write("                    <input type=\"date\" name=\"FSalida\" id=\"FSalida\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"\">Distancia</label>\r\n");
      out.write("                    <input type=\"text\" name=\"distancia\" id=\"distancia\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"\">Camion</label>\r\n");
      out.write("                    <select name=\"camion\" id=\"camion\" class=\"form-control\"  onchange=\"capacidadCamion();\">\r\n");
      out.write("                        <option selected=\"true\" disabled=\"disabled\">seleccionar</option>\r\n");
      out.write("                        ");
 for(Camion c: camiones){ 
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print(c.getId());
      out.write('"');
      out.write('>');
      out.print(c.getMatricula());
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("                            ");


                            }
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-9\">\r\n");
      out.write("                            <label for=\"\">Destino</label>\r\n");
      out.write("                            <input type=\"text\" name=\"destino\" id=\"destino\" class=\"form-control\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"idDestino\" id=\"idDestino\" class=\"form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <button class=\"btn btn-primary btn-xs\" style=\"margin-top: 30px;\" onclick=\"getDireccion(2);\">Obtener Datos</button>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"\">Fecha Estimada de Llegada</label>\r\n");
      out.write("                    <input type=\"date\" name=\"FELlegada\" id=\"FELlegada\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"\">Capacidad Camion</label>\r\n");
      out.write("                    <input type=\"text\" name=\"capCamion\" id=\"capCamion\" class=\"form-control\"  >\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <button  class=\"btn btn-success\" onclick=\"GuardarRuta();\" id=\"iniciarR\">Iniciar Ruta</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal fate\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <h4>Guardar Direccion</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\">Calle</label>\r\n");
      out.write("                                <input type=\"text\" name=\"Calle\" id=\"Calle\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\">Numero</label>\r\n");
      out.write("                                <input type=\"text\" name=\"Numero\" id=\"Numero\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\">Colonia</label>\r\n");
      out.write("                                <input type=\"text\" name=\"Colonia\" id=\"Colonia\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\">Ciudad</label>\r\n");
      out.write("                                <input type=\"text\" name=\"Ciudad\" id=\"Ciudad\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\">Estado</label>\r\n");
      out.write("                                <input type=\"text\" name=\"Estado\" id=\"Estado\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"\">CP</label>\r\n");
      out.write("                                <input type=\"text\" name=\"CP\" id=\"CP\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("                            <div class=\"col-md-4\">\r\n");
      out.write("                                <button class=\"btn btn-success\" onclick=\"GuardarDir();\" id=\"guardarbt\">Guardar</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Cerrar</button>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        function GuardarRuta()\r\n");
      out.write("        {\r\n");
      out.write("            swal(\"Alta de ruta recibida\",\"Espere mientras termina de cargar\", \"info\")\r\n");
      out.write("            $(\"#guardarR\").prop('disabled',true)\r\n");
      out.write("\r\n");
      out.write("            //recuperar los valores de las cajas de texto\r\n");
      out.write("            var choferId = $(\"#chofer\").val();\r\n");
      out.write("            var origenId = $(\"#idOrigen\").val();\r\n");
      out.write("            var fSalida = $(\"#FSalida\").val();\r\n");
      out.write("            var camionId = $(\"#camion\").val();\r\n");
      out.write("            var distancia = $(\"#distancia\").val();\r\n");
      out.write("            var destinoId = $(\"#idDestino\").val();\r\n");
      out.write("            var capCamion = $(\"#capCamion\").val();\r\n");
      out.write("            var fLlegada = $(\"#FELlegada\").val();\r\n");
      out.write("\r\n");
      out.write("            //hacer la peticion a mi api, mandandole los valores de las cajas\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type:'POST',\r\n");
      out.write("                url: \"http://localhost:8080/Gen1-Rutas/rutas/alta\",\r\n");
      out.write("                data: {\"choferId\":choferId, \"origenId\":origenId, \"fSalida\":fSalida, \"distancia\":distancia, \"camionId\":camionId, \"destinoId\":destinoId, \"capCamion\":capCamion, \"fLlegada\":fLlegada},\r\n");
      out.write("                success: function(resp){\r\n");
      out.write("\r\n");
      out.write("                    console.log(resp);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    swal(\"Exito\", \"Ruta iniciada correctamente\", \"success\")\r\n");
      out.write("                    $(\"#iniciarR\").prop('disabled',false)\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var camionesLis = ");
      out.print( new Gson().toJson(camiones) );
      out.write(";\r\n");
      out.write("\r\n");
      out.write("        function capacidadCamion()\r\n");
      out.write("        {\r\n");
      out.write("            var camionId = $(\"#camion\").val();\r\n");
      out.write("            var camionS = camionesLis.find(function(camion)\r\n");
      out.write("            {\r\n");
      out.write("                return camion.id == camionId;\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            if (camionS)\r\n");
      out.write("            {\r\n");
      out.write("                $(\"#capCamion\").val(camionS.capacidad);\r\n");
      out.write("            } else\r\n");
      out.write("            {\r\n");
      out.write("                $(\"#capCamion\").val(\"\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        function GuardarDir()\r\n");
      out.write("        {\r\n");
      out.write("            swal(\"Alta de dirección recibida\",\"Espere mientras termina de cargar\", \"info\")\r\n");
      out.write("            $(\"#guardarbt\").prop('disabled',true)\r\n");
      out.write("\r\n");
      out.write("            //recuperar los valores de las cajas de texto\r\n");
      out.write("            var calle = $(\"#Calle\").val();\r\n");
      out.write("            var numero = $(\"#Numero\").val();\r\n");
      out.write("            var colonia = $(\"#Colonia\").val();\r\n");
      out.write("            var ciudad = $(\"#Ciudad\").val();\r\n");
      out.write("            var estado = $(\"#Estado\").val();\r\n");
      out.write("            var cp = $(\"#CP\").val();\r\n");
      out.write("\r\n");
      out.write("            //hacer la peticion a mi api, mandandole los valores de las cajas\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type:'POST',\r\n");
      out.write("                url: \"http://localhost:8080/Gen1-API/api/direcciones\",\r\n");
      out.write("                data: {\"calle\":calle, \"numero\":numero, \"colonia\":colonia, \"ciudad\":ciudad, \"estado\":estado, \"cp\":cp},\r\n");
      out.write("                success: function(resp){\r\n");
      out.write("\r\n");
      out.write("                    console.log(resp);\r\n");
      out.write("                    $('#myModal').modal('hide');\r\n");
      out.write("                    if( $(\"#txtEsOD\").val()==1)\r\n");
      out.write("                    {\r\n");
      out.write("                        $(\"#idOrigen\").val(resp.message);\r\n");
      out.write("                    }\r\n");
      out.write("                    else\r\n");
      out.write("                    {\r\n");
      out.write("                        $(\"#idDestino\").val(resp.message);\r\n");
      out.write("                    }\r\n");
      out.write("                    swal(\"Exito\", \"Direccion guardada correctamente\", \"success\")\r\n");
      out.write("                    $(\"#guardarbt\").prop('disabled',false)\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function LimpiarDatos(){\r\n");
      out.write("            $(\"#Calle\").val(\"\");\r\n");
      out.write("            $(\"#Numero\").val(\"\");\r\n");
      out.write("            $(\"#Colonia\").val(\"\");\r\n");
      out.write("            $(\"#Ciudad\").val(\"\");\r\n");
      out.write("            $(\"#Estado\").val(\"\");\r\n");
      out.write("            $(\"#CP\").val(\"\");\r\n");
      out.write("        }\r\n");
      out.write("        function getDireccion(fuente){\r\n");
      out.write("            LimpiarDatos();\r\n");
      out.write("            $('#myModal').modal('show');\r\n");
      out.write("            var direccion = \"\";\r\n");
      out.write("            if (fuente == 1)//La direccion es un origen\r\n");
      out.write("            {\r\n");
      out.write("                direccion = $(\"#origen\").val();//boulevard san Feliped 224\r\n");
      out.write("            }\r\n");
      out.write("            else//La direccion es un destino\r\n");
      out.write("            {\r\n");
      out.write("                direccion = $('#destino').val();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $(\"#txtEsOD\").val(fuente);\r\n");
      out.write("            if (direccion != \"\")\r\n");
      out.write("            {\r\n");
      out.write("                //Llamamos/Consumir/hacer una peticion a la api de google maps\r\n");
      out.write("                //para obtener los datos completos de la direccion\r\n");
      out.write("                var geocoder = new google.maps.Geocoder();\r\n");
      out.write("                geocoder.geocode({ 'address':direccion }, function (results, status){\r\n");
      out.write("                    console.log(results);\r\n");
      out.write("                    console.log(status);\r\n");
      out.write("                    if (status == google.maps.GeocoderStatus.OK)\r\n");
      out.write("                    {\r\n");
      out.write("                        //Traemos los datos cmopletos de la direccion\r\n");
      out.write("                        var numresults = results[0].address_components.length;//7\r\n");
      out.write("                        //recorremos cada una de las propiedas de address_components\r\n");
      out.write("                        for(var indice = 0; indice < numresults; indice++){\r\n");
      out.write("                            var numresultstypes =\r\n");
      out.write("                            results[0].address_components[indice].types.length;//1\r\n");
      out.write("                            //Recorremos los tipos de cada compinente de la direccion\r\n");
      out.write("                            for(var propiedad = 0; propiedad < numresultstypes; propiedad++)\r\n");
      out.write("                            {\r\n");
      out.write("                                //Declaramos una varibale de nos permite saber eñl tipo\r\n");
      out.write("                                //de propiedad que estamos recorriendo\r\n");
      out.write("                                var Tipo = results[0].address_components[indice].types[propiedad];\r\n");
      out.write("                                //Descripcion va a contener el valor de la propiedad\r\n");
      out.write("                                var Descripcion =\r\n");
      out.write("                                    results[0].address_components[indice].long_name;\r\n");
      out.write("                                    //Validamos cada propiedad para escribirla en el textbox\r\n");
      out.write("                                    //que corresponda\r\n");
      out.write("                                    switch(Tipo){\r\n");
      out.write("                                        case \"route\": //calle\r\n");
      out.write("                                            $(\"#Calle\").val(Descripcion);\r\n");
      out.write("                                            break;\r\n");
      out.write("                                        case \"street_number\"://Numero\r\n");
      out.write("                                            $(\"#Numero\").val(Descripcion);\r\n");
      out.write("                                            break;\r\n");
      out.write("                                        case \"sublocality_level_1\"://colonia\r\n");
      out.write("                                            $(\"#Colonia\").val(Descripcion);\r\n");
      out.write("                                            break;\r\n");
      out.write("                                        case \"locality\": //ciudad\r\n");
      out.write("                                            $(\"#Ciudad\").val(Descripcion);\r\n");
      out.write("                                            break;\r\n");
      out.write("                                        case \"administrative_area_level_1\"://Estado\r\n");
      out.write("                                            $(\"#Estado\").val(Descripcion);\r\n");
      out.write("                                            break;\r\n");
      out.write("                                        case \"postal_code\": //C.P\r\n");
      out.write("                                            $(\"#CP\").val(Descripcion);\r\n");
      out.write("                                            break;\r\n");
      out.write("                                    }\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        //Asignamos a txtorigen o destino la direccion formateada\r\n");
      out.write("                        if(results[0].address_components.length > 0)\r\n");
      out.write("                        {\r\n");
      out.write("                            if(fuente == 1) //es origen\r\n");
      out.write("                            {\r\n");
      out.write("                                $(\"#origen\").val(results[0].formatted_address);\r\n");
      out.write("                            }\r\n");
      out.write("                            else\r\n");
      out.write("                            {\r\n");
      out.write("                                $(\"#destino\").val(results[0].formatted_address);\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    else\r\n");
      out.write("                    {\r\n");
      out.write("                        swal(\"Error de Google\", \"Google no obtuvo datos\", \"warning\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                //Avisamos al usuario que tebndra que capturar\r\n");
      out.write("                //todos los datos\r\n");
      out.write("                swal({\r\n");
      out.write("                    title: \"¿Estas seguro?\",\r\n");
      out.write("                    text: \"No podemos obtener datos sino proporciona una dirección\",\r\n");
      out.write("                    type: \"warning\",\r\n");
      out.write("                    showCancelButton: true,\r\n");
      out.write("                    confirmButtonClass: \"btn-warning\",\r\n");
      out.write("                    confirmButtonText: \"Si, quiero capturar la información\",\r\n");
      out.write("                    cancelButtonText: \"Cancelar\",\r\n");
      out.write("                    closeOnConfirm: true,\r\n");
      out.write("                    closeOnCancel: true\r\n");
      out.write("                }, function (isConfirm){\r\n");
      out.write("                    if (!isConfirm)\r\n");
      out.write("                    {\r\n");
      out.write("\r\n");
      out.write("                        $('#myModal').modal('hide');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
